id: ID90CEB4B
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-17T12:58:53.337142'
last_modified: '2022-06-17T12:58:53.337147'
parser: null
source_metadata:
  title: Mañjuśrī Series
  language: zh
  description: 'Texts related to Mañjuśrī (''jam dpal) or Mañjughoṣa (''jam pa''i
    dbyangs), the Buddha or Bodhisattva of Wisdom:'
  volume:
    f80C8:
      title: Ārya Mañjuśrī Tantra Garbha
      base_file: f80C8.txt
      order: 1
      parent: Ārya Mañjuśrī Tantra Citta
    f828C:
      title: Ārya Mañjuśrī Tantra Garbha—commentary
      base_file: f828C.txt
      order: 2
      parent: Ārya Mañjuśrī Tantra Citta
    fEE13:
      title: Chanting the Names of Noble Mañjuśrī
      base_file: fEE13.txt
      order: 3
      parent: Chanting the Names of Mañjuśrī
    fF5CA:
      title: 'Wisdom''s Bestowal: A Way to Accumulate the Recitation of the Tantra
        ''Chanting the Names of Mañjuśrī'' (Mañjuśrī Nāmasaṅgīti)'
      base_file: fF5CA.txt
      order: 4
      parent: Chanting the Names of Mañjuśrī
    fDC29:
      title: 'The Precious Jewelled Key: A Synopsis of the Aspiration of the Great
        Perfection Mañjuśrī'
      base_file: fDC29.txt
      order: 5
      parent: Dzogchen
    f5B78:
      title: 'Self-Radiance of Indestructible Awareness and Emptiness: An Aspiration
        towards the Meaning of the Indivisible Ground, Path and Fruition of the Great
        Perfection Mañjuśrī'
      base_file: f5B78.txt
      order: 6
      parent: Dzogchen
    f0397:
      title: Mañjuśrī Inscription
      base_file: f0397.txt
      order: 7
      parent: Inscriptions
    f7A7C:
      title: 'The Healing Medicine of Faith: A Prayer to the Lineage of the Peaceful
        Sādhana of Mañjuśrī'
      base_file: f7A7C.txt
      order: 8
      parent: Lineage Prayers
    f10B9:
      title: The Meaning of the Six Syllables of the King of Vidyā-Mantras, the Heroic
        Lord Mañjuśrī
      base_file: f10B9.txt
      order: 9
      parent: Mantra
    f4343:
      title: In Praise of the Lords of the Three Families
      base_file: f4343.txt
      order: 10
      parent: Praise
    f09E3:
      title: Praise and Prayer to the Five Families of Mañjuśrī
      base_file: f09E3.txt
      order: 11
      parent: Praise
    f27A9:
      title: 'The Fresh Saffron Flower: In Praise of Venerable Mañjughoṣa'
      base_file: f27A9.txt
      order: 12
      parent: Praise
    fAC43:
      title: 'The Light of Wisdom: Praise to Mañjuśrī'
      base_file: fAC43.txt
      order: 13
      parent: Praise
    fA9AE:
      title: 'The Lute of Vajra Harmony: Praise to the Protector Mañjuśrī'
      base_file: fA9AE.txt
      order: 14
      parent: Praise
    f4B03:
      title: 'The Swift Infusion of Blessings: In Praise of Mañjughoṣa'
      base_file: f4B03.txt
      order: 15
      parent: Praise
    fD9D4:
      title: 'In Praise of Mañjuśrī: Increasing Intelligence to the Full'
      base_file: fD9D4.txt
      order: 16
      parent: Praise
    fEE1A:
      title: 'In Praise of Mañjuśrī: The Great Treasure of Blessings'
      base_file: fEE1A.txt
      order: 17
      parent: Praise
    f9A9D:
      title: In Praise of the Protector Mañjughoṣa
      base_file: f9A9D.txt
      order: 18
      parent: Praise
    fECBE:
      title: 'Unchanging Auspiciousness: In Praise of Mañjuśrī'
      base_file: fECBE.txt
      order: 19
      parent: Praise
    f155D:
      title: Ultimate Praise of the Noble and Venerable Mañjuśrī
      base_file: f155D.txt
      order: 20
      parent: Praise
    f4522:
      title: Praise to Mañjughoṣa
      base_file: f4522.txt
      order: 21
      parent: Praise
    f64A5:
      title: 'A Few Remarks: An Explanation of the Praise to Noble Mañjuśrī known
        as Glorious Wisdom’s Excellent Qualities'
      base_file: f64A5.txt
      order: 22
      parent: Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
    f13B2:
      title: 'Bestower of the Light of Intelligence: A Prayer to the Lineage of the
        Profound Sādhana Based Upon the Praise to Venerable Mañjughoṣa'
      base_file: f13B2.txt
      order: 23
      parent: Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
    f32E1:
      title: The Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
      base_file: f32E1.txt
      order: 24
      parent: Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
    f3F16:
      title: The Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
      base_file: f3F16.txt
      order: 25
      parent: Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
    f6FC6:
      title: A Prayer to Mañjuśrī
      base_file: f6FC6.txt
      order: 26
      parent: Prayers
    fF121:
      title: Prayer to Bhagavān Mañjughoṣa
      base_file: fF121.txt
      order: 27
      parent: Prayers
    f288A:
      title: Prayer to the Lion of Speech
      base_file: f288A.txt
      order: 28
      parent: Prayers
    f5A74:
      title: Prayer to Mañjuśrī
      base_file: f5A74.txt
      order: 29
      parent: Prayers
    fE0AA:
      title: A Prayer to Mañjughoṣa
      base_file: fE0AA.txt
      order: 30
      parent: Prayers
    fA412:
      title: 'The Torch of Wisdom: A Method of Offering Butter Lamps Based on Ārya
        Mañjuśrī'
      base_file: fA412.txt
      order: 31
      parent: Rituals
    f4493:
      title: Light from the Wisdom Sun
      base_file: f4493.txt
      order: 32
      parent: Sādhanas
    f4AC5:
      title: A Sādhana of Golden Mañjughoṣa
      base_file: f4AC5.txt
      order: 33
      parent: Sādhanas
    f9CAC:
      title: 'Swift Bestowal of Blessings: A Peaceful Sādhana of Mañjuśrī'
      base_file: f9CAC.txt
      order: 34
      parent: Sādhanas
    f9633:
      title: A Brief Mañjuśrī Sādhana
      base_file: f9633.txt
      order: 35
      parent: Sādhanas
    f33AA:
      title: Sādhana of Mañjughoṣa
      base_file: f33AA.txt
      order: 36
      parent: Sādhanas
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
